In [10]:
import numpy as np
import scipy.sparse as sps 
data = sps.load_npz("./example_data/cashflow_1961-06-30.npz").toarray()
# print(data.files)  


In [11]:
data['indices']

array([ 89, 119, 150, ..., 169, 183, 344])

In [12]:
data['indptr']

array([   0,    1,    2,    3,    4,    6,    8,   13,   18,   23,   28,
         33,   39,   45,   56,   68,  119,  171,  173,  179,  181,  187,
        188,  240,  242,  244,  250,  252,  264,  267,  270,  272,  278,
        281,  285,  289,  293,  297,  300,  307,  312,  317,  322,  327,
        333,  339,  342,  349,  362,  371,  380,  433,  440,  447,  455,
        463,  471,  480,  483,  497,  512,  519,  529,  540,  551,  563,
        576,  589,  592,  599,  614,  630,  646,  664,  682,  701,  704,
        711,  724,  777,  802,  828,  854,  881,  909,  937,  967,  970,
        977, 1009, 1042, 1077, 1122, 1169, 1216, 1265, 1314, 1365, 1369,
       1377, 1381, 1389, 1403, 1457, 1461, 1469, 1473, 1481, 1485, 1493,
       1507, 1561, 1565, 1573, 1578, 1587, 1592, 1601, 1616, 1671, 1676,
       1685, 1686, 1691, 1700, 1701, 1706, 1715, 1730, 1785, 1786, 1791,
       1800, 1802, 1808, 1818, 1820, 1826, 1836, 1852, 1908, 1910, 1916,
       1926, 1928, 1934, 1944, 1946, 1952, 1962, 19

In [13]:
data['format']

array(b'csr', dtype='|S3')

In [14]:
data['shape']

array([  280, 10727], dtype=int64)

In [15]:
data['data']

array([100.875 , 100.9375, 101.125 , ..., 100.    , 100.    , 100.    ])

In [11]:
import numpy as np
data_P = np.load("./example_data/price_1961-06-30.npy")
print(data)  

[[  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.       0.    ]
 ...
 [  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.     101.9375]]
