In [1]:
import numpy as np
import scipy.sparse as sps 
data = sps.load_npz("./example_data/cashflow_1961-06-30.npz").toarray()
# print(data.files)  


In [11]:
data['indices']

array([ 89, 119, 150, ..., 169, 183, 344])

In [ ]:
data['indptr']

In [13]:
data['format']

array(b'csr', dtype='|S3')

In [14]:
data['shape']

array([  280, 10727], dtype=int64)

In [15]:
data['data']

array([100.875 , 100.9375, 101.125 , ..., 100.    , 100.    , 100.    ])

In [2]:
import numpy as np
data_P = np.load("./example_data/price_1961-06-30.npy")
print(data)  

[[  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.       0.    ]
 ...
 [  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.       0.    ]
 [  0.       0.       0.     ...   0.       0.     101.9375]]


In [22]:
aa = np.arange(1,13)
ind = np.arange(0,12)

In [23]:
ind[aa<=9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
cc = [1,2,3]

In [28]:
min(max(cc),2)

2

In [38]:
neu = []
neu.append(1+2)
neu

[3]